name: Update Finance Info

# Thiết lập để chạy mỗi 1 phút một lần
on:
  schedule:
    - cron: '*/1 * * * *'  # Chạy mỗi 1 phút

  # Kích hoạt thủ công nếu cần
  workflow_dispatch:

jobs:
  update-finance-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Fetch dữ liệu từ cổng thông tin Bộ Tài chính
       - name: Fetch Ministry of Finance information
        run: |
          mkdir -p finance-info
          curl -L https://www.mof.gov.vn/webcenter/portal/btc/r/lvtc/ > finance-info/index.html

      # Commit thay đổi và đẩy lên repository
      - name: Commit and push changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update finance information from Ministry of Finance"
          git push
