name: Update Finance Info

# Thiết lập để chạy mỗi phút và có thể kích hoạt thủ công
on:
  schedule:
    - cron: '*/1 * * * *'  # Chạy mỗi 1 phút
  workflow_dispatch:  # Cho phép kích hoạt thủ công nếu cần

jobs:
  update-finance-site:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Cập nhật curl lên phiên bản mới nhất để đảm bảo tính tương thích
      - name: Update curl to the latest version
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      # Bước 2: Checkout repository để lấy mã nguồn hiện tại
      - name: Checkout repository
        uses: actions/checkout@v2

      # Bước 3: Fetch dữ liệu từ cổng thông tin Bộ Tài chính
      # Chỉ dùng curl mà không cần -L, JavaScript sẽ xử lý chuyển hướng sau
      - name: Fetch Ministry of Finance information
        run: |
          mkdir -p finance-info
          curl -k https://www.mof.gov.vn/webcenter/portal/btc/r/lvtc/ > finance-info/index.html

      # Bước 4: Kiểm tra xem có thay đổi hay không trước khi commit
      - name: Commit changes if there are updates
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update finance information from Ministry of Finance"
            git push
          else
            echo "No changes to commit"
