name: Update Finance Info

# Thiết lập để chạy mỗi 1 phút và có thể kích hoạt thủ công
on:
  schedule:
    - cron: '*/1 * * * *'  # Chạy mỗi 1 phút
  workflow_dispatch:  # Kích hoạt thủ công nếu cần

jobs:
  update-finance-site:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout repository để lấy mã nguồn hiện tại
      - name: Checkout repository
        uses: actions/checkout@v2

      # Bước 2: Fetch dữ liệu từ cổng thông tin Bộ Tài chính với theo dõi chuyển hướng (302)
      - name: Fetch Ministry of Finance information
        run: |
          mkdir -p finance-info
          curl -L https://www.mof.gov.vn/webcenter/portal/btc/r/lvtc/ > finance-info/index.html

      # Bước 3: Kiểm tra xem có thay đổi hay không trước khi commit
      - name: Commit changes if there are updates
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update finance information from Ministry of Finance"
            git push
          else
            echo "No changes to commit"
          fi
