name: Update Finance Info

# Thiết lập để chạy tự động mỗi ngày vào 12:00 giờ trưa (theo UTC)
on:
  schedule:
    - cron: '0 12 * * *'  # Chạy hàng ngày vào 12 giờ trưa (theo giờ UTC)

jobs:
  update-finance-site:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout repository để lấy mã nguồn hiện tại
      - name: Checkout repository content
        uses: actions/checkout@v2

      # Bước 2: Fetch dữ liệu từ cổng thông tin của Bộ Tài chính
      - name: Fetch Ministry of Finance information
        run: |
          # Tạo thư mục để lưu nội dung mới
          mkdir -p finance-info
          # Sử dụng curl để lấy nội dung trang web (có thể thay đổi URL theo trang cụ thể bạn muốn lấy)
          curl https://mof.gov.vn/webcenter/portal/btc/r/lvtc/ -> finance-info/index.html

      # Bước 3: Commit các thay đổi (nếu có dữ liệu mới)
      - name: Commit and push changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update finance information from Ministry of Finance"
          git push
